### ISSUE TITLE
NullPointerException when using an HTTP client

### ISSUE THREAD

**Issue by anatolydwnld** [twitter/finagle#644] opened 2017-08-16 12:30 UTC
Calling `Http.Client()` before initializing `Http.client` mangles `Http.client` causing NPEs

### Expected behavior
One of two things is expected: either the API should prevent users from invoking Http.Client() directly or it should not cause subsequent NPEs

### Actual behavior

There are NPEs

### Steps to reproduce the behavior
Minimal repro is here: https://github.com/fanatoly/finagle-init-repro/blob/master/Repro.scala

**Comment by bryce-anderson** [comment] 2017-08-16 15:17
Sure enough: by using `Http.Client()` instead of initializing `Http` first it starts with `Http.Client` which then begins `Http` which uses uninitialized fields on `Http.Client` resulting in nulls. This can be fixed by making `Client.stack` lazy or a def.

**Comment by anatolydwnld** [comment] 2017-08-16 16:08
Is there a valid use case for calling Http.Client() directly? If not maybe the constructor should be marked `private[Http]`?

**Comment by bryce-anderson** [comment] 2017-08-16 16:27
Depends on your stance on API's: you don't _need_ to since you can use `Http.client.copy(..)` or the helper methods to do more directed configuration changes, but there is no reason not to have an open constructor function in case someone wants to simply replace the stack or params (or both).

IMO, the root of the problem is the use of eager evaluation in the object fields: I think we're just being too stingy with allocations by trying to cache the base case and it bit this time.

**Comment by mosesn** [comment] 2017-08-28 18:28
We should increase the priority of this. . . I don't know why our travisci tests are passing, it seems to fail locally.

**Comment by vkostyukov** [comment] 2017-09-01 18:17
I think this is now fixed by 2fa89b52798f57250fa22a6be3ff62551f02207d.

**Closed by vkostyukov** 2017-09-01 18:17 UTC

**Comment by mosesn** [comment] 2017-09-09 15:03
@anatolydwnld we've published a new version of finagle.  Can you try finagle 7.1.0?

**Comment by anatolydwnld** [comment] 2017-09-11 16:31
Upgrading to 7.1.0 fixes my reproducer. This can probably be closed. Thanks!
