### ISSUE TITLE
does not resolve hostname during reconnection

### ISSUE THREAD

**Issue by DanielCharczynski** [twitter/finagle#664] opened 2017-11-24 11:17 UTC
When an IP is changed in name server finagle is not able to reconnect to the new IP

### Expected behavior

Proper reconnection

### Actual behavior

Connecting to IP resolved at the begining

### Steps to reproduce the behavior

set networkaddress.cache.ttl=2 in JVM  java.security

send requests in loop to specific host name resolved locally in /etc/hosts
change an IP in /etc/hosts
disconnect form network/internet in order to break connection
connect to network after few seconds
check out logs - connection to old IP

**Comment by mosesn** [comment] 2017-11-24 12:52
@DanielCharczynski how do you configure your client, and which version of finagle are you using?  We have some behavior in finagle to re-resolve periodically, so I think it should handle the use case you're describing.  https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/InetResolver.scala#L133-L154

**Comment by DanielCharczynski** [comment] 2017-11-24 13:44
Thanks for quick response

unfortunately I have to use JVM 7 compatible one - > 6.35.0

Which version solve this problem?

**Comment by mosesn** [comment] 2017-11-27 16:03
@DanielCharczynski it looks like we first added this functionality in [6.20.0][0], but we've changed our implementation quite a bit, so you might be running into an old bug.

Unfortunately, we're not going to publish any future releases to be JDK7 compatible, so we can't fix your problem.  Are you planning on switching to JDK8 soon?  If not, your best bet might be to fork a current branch of finagle, remove the JDK8-only APIs and publish it yourself for JDK7.

I'm going to close this ticket for now, but please let us know if you can reproduce this issue in a current finagle version.

[0]: https://github.com/twitter/finagle/commit/1c06105a446994f314773de3713c8d98ebcab482#diff-db7b87f0a4106332436d9699a49b9486

**Closed by mosesn** 2017-11-27 16:03 UTC
