### ISSUE TITLE
Upgrade libthrift?

### ISSUE THREAD

**Issue by eirslett** [twitter/finagle#206] opened 2013-10-15 14:01 UTC
Will the dependency on libthrift ever be upgraded from 0.5.* to 0.9.*, the latest version?

**Comment by itszero** [comment] 2015-02-09 20:24
Looks like libthrift-0.5.0 disappeared on maven.org. Could we bump up the priority a little bit?

**Comment by nshkrob** [comment] 2015-02-10 18:35
Upgrading to a recent libthrift version would involve some work for us internally, so it's not a priority at the moment.

In the meantime, you can use the http://maven.twttr.com to get libthrift-0.5.0: 
http://maven.twttr.com/org/apache/thrift/libthrift/0.5.0/

**Comment by MayiTiny** [comment] 2015-07-01 09:12
I found that it have a conflict between libthrift0.8.0(in storm) and libthrift0.5.0(in finagle). But I must use both storm and finagle for some reason.I see there is still no schedule to upgrade or remove thrift dependency.
So I upgrade thrift dependency to 0.8 and change the thrift file which generated by scrooge manually.
It works well at present. 
I hope it can work continuous...

**Comment by taylorleese** [comment] 2015-07-01 18:52
Upgrading libthrift is on the radar for CSL, but it's not something we're
planning to actively pursue until after the Monobuild lands.

- Taylor

**Comment by taylorleese** [comment] 2015-07-01 19:06
Upgrading libthrift is on the long-term radar. There are some logistics that need to be sorted out first.

**Comment by drozzy** [comment] 2015-10-28 07:08
With all due respect, how is this not a priority? The dependency has _disappeared_ off the maven altogether (try that - gives you an error):
http://mvnrepository.com/artifact/org.apache.thrift/libthrift/0.5.0

I am trying to install `scrooge-core 4.2.0` and `finagle-thrift_2.11" % 6.30.0` but this is really making the whole thing impossible.

**Comment by mosesn** [comment] 2015-10-28 08:11
Hi @drozzy, sorry you've had trouble with this.  As @nshkrob mentioned, you can use maven.twttr.com in the mean time.  Note that it uses ssl now, so you'll want to go to https://maven.twttr.com/org/apache/thrift/libthrift/0.5.0/

**Comment by eirslett** [comment] 2015-10-28 09:45
You can easily use libthrift 0.9.2 with finagle, no problem. As long as you use the Java generator. (Unless you hit an edge-case.) Just override the version you get from finagle.

**Comment by drozzy** [comment] 2015-10-28 12:41
@mosesn Thanks, I think I'll use the jar after all. Seems like a hack though :-)

@eirslett Forgive me, but I don't think I know what you mean... I'm going to use the scrooge sbt plugin.

**Comment by eirslett** [comment] 2015-10-28 12:56
You can use sbt and exclude the version of libthrift that finagle gives you. And then you must include your own version instead. (0.9.2?)
Use the latest version of the scrooge sbt plugin. Then it should just work - I think... (at least it worked for me)

**Comment by drozzy** [comment] 2015-10-28 13:16
@eirslett But scrooge-sbt-plugin requires Scala 2.10, while scrooge-core is available for Scala 2.11... :(

**Comment by eirslett** [comment] 2015-10-28 14:37
Too bad the sbt plugin isn't published... but it's only one file, you could simply copy-paste it directly into your project:

https://github.com/twitter/scrooge/blob/develop/scrooge-sbt-plugin/src/main/scala/com/twitter/ScroogeSBT.scala

**Comment by drozzy** [comment] 2015-10-28 15:02
@eirslett So here is a stupid question... where would I copy it? Into `project/ScroogeSBT.scala`?

**Comment by eirslett** [comment] 2015-10-28 15:08
exactly.

**Comment by mosesn** [comment] 2016-05-29 03:38
This is a duplicate of https://github.com/twitter/finagle/issues/133, so I'm going to close this ticket.  Unfortunately, it's still a low priority internally to fix this.

**Closed by mosesn** 2016-05-29 03:38 UTC
