### ISSUE TITLE
SslVerifiier is triggered before Handshake

### ISSUE THREAD

**Issue by iPlessmann** [twitter/finagle#679] opened 2018-02-22 08:36 UTC
When trying to retrieve the peer certificates from the session by specifiying my own SslServerSessionVerifier it fails because this is invoked before the Handshake is fully finished

### Expected behavior

In my SslServerSessionVerifier that is passed to Http.server.withTransport.tls(config: SslServerConfiguration, engineFactory: SslServerEngineFactory,  sessionVerifier: SslServerSessionVerifier) i should be able to retrieve the peer certificates by using session.getPeerCertificateChain

### Actual behavior

when invoking session.getPeerCertificateChain an exception is thrown and the Handshake is finished after the exception, here is my log for this:

```finagle/netty4-1, READ: TLSv1.2 Change Cipher Spec, length = 1
finagle/netty4-1, READ: TLSv1.2 Handshake, length = 96
*** Finished
verify_data:  { 114, 56, 217, 248, 113, 33, 70, 87, 181, 139, 98, 218 }
***
finagle/netty4-1, WRITE: TLSv1.2 Change Cipher Spec, length = 1
*** Finished
verify_data:  { 211, 79, 182, 216, 76, 214, 199, 144, 89, 154, 29, 97 }
***
finagle/netty4-1, WRITE: TLSv1.2 Handshake, length = 96
%% Cached server session: [Session-1, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384]
2018-02-22 09:18:41,800 INFO MyServer$ Reached the SslServerSessionVerifier and got Cipher TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 from the session
2018-02-22 09:18:41,801 INFO MyServer$ Exception on SslServerSessionVerifier when calling session.getPeerCertificateChain or session.getPeerCertificates = peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificateChain(SSLSessionImpl.java:482)
	at MyClass$$MySslServerSessionVerifierImpl$1.$MySslServerSessionVerifierImplfun$apply$1(Utils.scala:102)
	at scala.util.Try$.apply(Try.scala:209)
	at MyClass$$MySslServerSessionVerifierImpl$1.apply(Utils.scala:102)
	at com.twitter.finagle.netty4.ssl.server.SslServerVerificationHandler.com$twitter$finagle$netty4$ssl$server$SslServerVerificationHandler$$verifySession(SslServerVerificationHandler.scala:28)
	at com.twitter.finagle.netty4.ssl.server.SslServerVerificationHandler$$anon$1.operationComplete(SslServerVerificationHandler.scala:64)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1432)
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:865)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:745)
2018-02-22 09:18:41,823 DEBUG i.n.h.s.SslHandler [id: 0xe4fc82f2, L:/127.0.0.1:8081 - R:/127.0.0.1:53295] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
```

### Steps to reproduce the behavior

Implement a SslServerSessionVerifier, pass it to Http.server.withTransport.tls(config: SslServerConfiguration, engineFactory: SslServerEngineFactory,  sessionVerifier: SslServerSessionVerifier) and then call session.getPeerCertificateChain

**Comment by mosesn** [comment] 2018-02-26 18:47
Hmm, interesting.  It looks like it's [intentional][0] that we don't mark the handshake as "finished" here, but clearly you should be able to access the peer certificate so you can validate it.  I'll ask around to try to better understand what the intent here is, I agree that this seems wrong.

[0]: https://github.com/twitter/finagle/blob/559ae4ad3eb6bae4c2f885fb3149b492c6bf46a0/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/server/SslServerVerificationHandler.scala

**Comment by mosesn** [comment] 2018-02-26 20:01
@iPlessmann from talking to @ryanoneill it sounds like SSLPeerUnverifiedException indicates that the client might not be passing you certificates.  The way to indicate that we hard fail when that happens is to pass a `clientAuth` parameter of `ClientAuth.Needed` in `SslServerConfiguration`.  Can you try that out so we can check whether you're actually passing the certs?  For what it's worth, internally we do inspect the certificates during the SslSessionVerification step, so it should be possible for you to do it too.

**Comment by legopiraat** [comment] 2018-03-12 14:06
@mosesn I've just tried the same thing and i've made sure my client certificate is send + i set set my server config to: 
```
  Http.server
      .withTransport.tls(SslServerConfiguration(clientAuth = ClientAuth.Needed), serverFilter)
```

The `session.getPeerCertificateChain` still throws the same error.

**Comment by legopiraat** [comment] 2018-03-13 11:26
After some extra digging around i managed to get it working. 
Turns out there is a some extra server configuration needed.

```
Http.server
      .withTransport.tls(SslServerConfiguration(clientAuth = ClientAuth.Needed), (config: SslServerConfiguration) => {

      val context: SslContext = SslContextBuilder
        .forServer(privateKey, password, certificate)
        .trustManager(trustedCertificate).build()

      val engine = context.newEngine(io.netty.buffer.UnpooledByteBufAllocator.DEFAULT)
      engine.setNeedClientAuth(true)
      Engine(engine)
    }, sessionVerifier)
```

With this configuration i was able to retrieve the peerCertificates in the sessionVerifier.

**Comment by mosesn** [comment] 2018-03-29 18:28
I think this is working as intended, so I'm going to close this for now until we get more information.

**Closed by mosesn** 2018-03-29 18:28 UTC
