### ISSUE TITLE
HTTP2: Downgrading connection to HTTP1.1 doesn't work when using TLS

### ISSUE THREAD

**Issue by spockz** [twitter/finagle#650] opened 2017-09-09 07:22 UTC
HTTP2: Downgrading connection to HTTP1.1 doesn't work when configuring the client to use TLS.

### Expected behavior

I expect the client to negotiate down to 1.1 even when using TLS.

### Actual behavior

I get an exception per request:

```
2017-09-08 20:18:34.760  WARN 85196 --- [nagle/netty4-13] io.netty.channel.ChannelInitializer      : Failed to initialize a channel. Closing: [id: 0xb724ebcd]

com.twitter.finagle.ssl.SslConfigurationException: ApplicationProtocols.Supported is not supported at this time for SslContextClientEngineFactory
        at com.twitter.finagle.ssl.SslConfigurationException$.notSupported(SslConfigurationException.scala:16) ~[finagle-core_2.12-7.1.0.jar:7.1.0]
        at com.twitter.finagle.ssl.SslConfigurations$.checkApplicationProtocolsNotSupported(SslConfigurations.scala:183) ~[finagle-core_2.12-7.1.0.jar:7.1.0]
        at com.twitter.finagle.ssl.client.SslContextClientEngineFactory.apply(SslContextClientEngineFactory.scala:37) ~[finagle-core_2.12-7.1.0.jar:7.1.0]
        at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.$anonfun$initChannel$1(Netty4ClientSslHandler.scala:123) ~[finagle-netty4_2.12-7.1.0.jar:7.1.0]
        at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.$anonfun$initChannel$1$adapted(Netty4ClientSslHandler.scala:120) ~[finagle-netty4_2.12-7.1.0.jar:7.1.0]
        at scala.Option.foreach(Option.scala:257) ~[scala-library-2.12.3.jar:na]
        at com.twitter.finagle.netty4.ssl.client.Netty4ClientSslHandler.initChannel(Netty4ClientSslHandler.scala:120) ~[finagle-netty4_2.12-7.1.0.jar:7.1.0]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:605) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:186) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:151) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at com.twitter.finagle.netty4.channel.AbstractNetty4ClientChannelInitializer.initChannel(AbstractNetty4ClientChannelInitializer.scala:76) [finagle-netty4_2.12-7.1.0.jar:7.1.0]
        at com.twitter.finagle.netty4.channel.RawNetty4ClientChannelInitializer.initChannel(RawNetty4ClientChannelInitializer.scala:18) [finagle-netty4_2.12-7.1.0.jar:7.1.0]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:605) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:45) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1395) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1130) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:655) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.14.Final.jar:4.1.14.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
        at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23) [finagle-core_2.12-7.1.0.jar:7.1.0]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
```

### Steps to reproduce the behavior

```scala
Http.client.withParams(finagle.Http.Http2).withTransport().tls(clientSSLContext:SSLContext)
```
Connect this to an TLS HTTP1.1 server.

**Comment by mosesn** [comment] 2017-09-09 15:33
@spockz can you use SslClientConfiguration instead of supplying your own SslContext?

**Comment by spockz** [comment] 2017-09-11 18:12
@mosesn I would like to, however, how are we supposed to use them with certificates that have passwords? We don't use pem files usually, so even if this test works it would be an issue for us.

**Comment by spockz** [comment] 2017-09-11 18:25
Downgrading to `SslClientConfiguration` indeed makes it work. Why is providing the `SSLContext` not supported anymore? I would expect the behaviour of non-deprecated configuration options to be equivalent.

**Comment by mosesn** [comment] 2017-09-11 19:51
@spockz I don't think SslContext exposes an API for ALPN, so you might have to configure it yourself.  What certificate format do you use?

For what it's worth, I think the long-term plan is to try to move off of SslContext, but as you've mentioned, we don't have feature parity yet.  Maybe the right thing is to rebrand it as, "raw tls" instead of a first class finagle supported way of doing it.

cc @ryanoneill

**Comment by spockz** [comment] 2017-09-12 04:02
@mosesn No afaik it doesn't. However, it can be constructed easily from a wide range of certificate formats with and without keys which was very convenient for us.

We use a jks with password containing encrypted private/public key pairs in x509 format. Maybe the configuration could work on Keystore and Truststore abstractions instead of direct references to pems?

**Comment by mosesn** [comment] 2017-09-12 20:03
@spockz maybe instead of KeyStore and TrustStore directly, we could take Certificates?  @ryanoneill wdyt?

**Comment by spockz** [comment] 2017-09-17 11:09
Any thoughts on this @mosesn and @ryanoneill?

**Comment by mosesn** [comment] 2018-02-26 21:00
Sorry for dropping the ball on this @spockz.  I think exposing an API where we take Certificates directly is worth looking into, I'll talk to @ryanoneill and see what he thinks.

**Comment by spockz** [comment] 2018-02-26 21:44
When debugging #679 I noticed there was a way to use .tls() with a SSLContext and a verifier for servers. I need to verify whether that works for us for clients. Also, we are currently using the SSLContext for configuring things like OCSP. Is that still available through the normal Java’s security options or do we need another mechanism?

**Comment by ryanoneill** [comment] 2018-02-27 23:04
Regarding taking certificates directly, it's something we investigated, but decided against, at least for now. The issue is not about the certificate, but about the associate private key. Having a Finagle stack param which contains a PrivateKey leads us to too many places where it can be exposed accidentally through logging or admin registry access. We don't have a business case for it internally at the moment either, so we haven't discussed it any further. 

'I need to verify whether that works for us for clients'. Verifiers do work on the client as well. 

With regards to OCSP, it's not something we use internally with Finagle and we don't have plans to use it in the near future either. Can you provide me with a better idea of how you would normally configure OCSP?

**Comment by spockz** [comment] 2018-03-02 18:41
> 'I need to verify whether that works for us for clients'. Verifiers do work on the client as well.

I’m aware that verifiers work on the client. We currently use them for san/server hostname checking. I was referring to whether we can configure the client with empty configuration, initialise the engine factory with the SSLContext and add a verifier.

The de facto standard in java is to enable OCSP through a -Djavax.security property which exact name eludes me for now. I haven’t gotten around to benchmark and resilience test this. I need to do that because going to http2 means going to OpenSSL bindings which don’t react to the standard Java’s security configuration.

Related, ALPN and OCSP-stapling is available in jre9. Are there any plans to support j9? Currently using j9 still leads to some unsupported engine error.

**Comment by ryanoneill** [comment] 2018-03-09 20:04
Apologies for the delay. I'm starting to understand the picture here. 

Our plans for supporting JDK9 externally aren't set in stone yet. Internally, it looks like we're moving directly from 8 to a higher version (11?) when it's ready. We've gotten reports both internally and externally and have fixed a [few issues recently](https://github.com/twitter/finagle/commit/1313d9ba77b35da0a9a6fce3599dfc7c4c5e137d).

To have the combination of features that you're looking for (Java's SSLContext, OCSP, ALPN (which as you mentioned for Java comes in JDK9)), you'll need to write your own [SslClientEngineFactory](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/ssl/client/SslClientEngineFactory.scala). It should be almost identical to the [SslContextClientEngineFactory](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/ssl/client/SslContextClientEngineFactory.scala) but just needs the ability to set the `ApplicationProtocols` in the same way we're now setting [hostname verification](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/ssl/SslConfigurations.scala#L131).

**Comment by spockz** [comment] 2018-04-21 21:17
Using JDK9 creating our own `SslContextClientEngineFactory` as below does execute and I'm able to connect to our existing http/1.1 servers. (This obviously won't work on JDK8.)

However, pointing the client to `http2.akamai.com` results in "This browser is not HTTP/2 enabled." when using ApplicationProtocols.Unspecified, and "com.twitter.finagle.ConnectionFailedException: null at remote address: http2.akamai.com/2a02:26f0:7b:299:0:0:0:2a71:443." when I set the ApplcationProtocols to "h2". Whereas with the normal JDKClientEngineFactory I get back "You are using HTTP/2 right now!", regardless of the protocols I specify. 

Also, I couldn't figure out how to debug on a h2 enabled finagle server whether I'm receiving a request over h2 or over http/1.1 How can I access that information?

This is on Finagle 18.2.0 btw.

```scala
final class SslContextClientEngineFactory(sslContext: SSLContext) extends SslClientEngineFactory {

  def apply(address: Address, config: SslClientConfiguration): Engine = {

    val engine = SslClientEngineFactory.createEngine(sslContext, address, config)
    SslClientEngineFactory.configureEngine(engine, config)
    config.applicationProtocols match {
      case ApplicationProtocols.Unspecified => ()
      case ApplicationProtocols.Supported(appProtocols) =>
        engine.self.getSSLParameters.setApplicationProtocols(appProtocols.toArray)
    }
    engine
  }
}
```

**Comment by spockz** [comment] 2018-05-03 21:57
@ryanoneill The Netty SslContextBuilder supports passing in [KeyManagerFactory](https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#keyManager-javax.net.ssl.KeyManagerFactory-)s and [TrustManagerFactory](https://netty.io/4.1/api/io/netty/handler/ssl/SslContextBuilder.html#trustManager-javax.net.ssl.TrustManagerFactory-). Would you be willing to accept a merge request which extends the `KeyCredentials` and `TrustCredentials` to be constructed with a `KeyManagerFactory` and `TrustManagerFactory` respectively which are then used to call the matching methods of `SslContextBuilder` in the `Netty4ClientSslConfigurations` and `Netty4ServerSslConfigurations`?

**Comment by ryanoneill** [comment] 2018-05-03 22:02
@spockz That seems reasonable to me, especially considering that Netty made modifications to allow those to work with netty-tcnative.

**Comment by ryanoneill** [comment] 2019-07-09 22:30
Seems like the pull request for this issue was submitted and accepted, but we never closed the associated issue. I'm going to close this. If it's still a problem, please file another issue.

**Closed by ryanoneill** 2019-07-09 22:30 UTC
