### ISSUE TITLE
ServiceClosedExceptions when using maximum pool size with an HTTP client

### ISSUE THREAD

**Issue by jlawrienyt** [twitter/finagle#748] opened 2018-12-28 16:24 UTC
finagle-core: http clients with maximum pool sizes permanently close under load.

### Expected behavior

We should be able to configure a maximum pool size to limit load on an upstream endpoint and have it continue to function even after DNS name changes.

### Actual behavior

When the client with the configured maximum pool size is under heavy load (i.e. there are requests waiting for a connection) and the underlying destination name resolves to a different endpoint, the endpoint is closed and the client never recovers until the application is restarted. Sample exception:

```
Dec 28, 2018 10:49:18 AM com.twitter.finagle.util.DefaultMonitor logWithRemoteInfo
WARNING: Exception propagated to the default monitor (upstream address: /127.0.0.1:49908, downstream address: n/a, label: ).
com.twitter.finagle.loadbalancer.LazyEndpointFactory$$anon$1: Tried to acquire endpoint after it was closed
	at com.twitter.finagle.loadbalancer.LazyEndpointFactory.apply(EndpointFactory.scala:106)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded$Node.com$twitter$finagle$loadbalancer$LeastLoaded$LeastLoadedNode$$super$apply(P2CLeastLoaded.scala:47)
	at com.twitter.finagle.loadbalancer.LeastLoaded$LeastLoadedNode.apply(LeastLoaded.scala:27)
	at com.twitter.finagle.loadbalancer.LeastLoaded$LeastLoadedNode.apply$(LeastLoaded.scala:25)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded$Node.apply(P2CLeastLoaded.scala:47)
	at com.twitter.finagle.loadbalancer.Balancer.apply(Balancer.scala:211)
	at com.twitter.finagle.loadbalancer.Balancer.apply$(Balancer.scala:199)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded.apply(P2CLeastLoaded.scala:35)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.loadbalancer.TrafficDistributor$Distributor.apply(TrafficDistributor.scala:90)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.loadbalancer.TrafficDistributor.apply(TrafficDistributor.scala:308)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.filter.RequestLogger$$anon$1.apply(RequestLogger.scala:55)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.filter.RequestLogger$$anon$1.apply(RequestLogger.scala:55)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.factory.RefcountedFactory.apply(RefcountedFactory.scala:23)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.filter.RequestLogger$$anon$1.apply(RequestLogger.scala:55)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.factory.TimeoutFactory.apply(TimeoutFactory.scala:63)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.filter.RequestLogger$$anon$1.apply(RequestLogger.scala:55)
	at com.twitter.finagle.ServiceFactory$$anon$2.apply(ServiceFactory.scala:46)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.filter.RequestLogger$$anon$1.apply(RequestLogger.scala:55)
	at com.twitter.finagle.Filter$$anon$3.apply(Filter.scala:104)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.filter.RequestLogger$$anon$1.apply(RequestLogger.scala:55)
	at com.twitter.finagle.ServiceFactory.apply(ServiceFactory.scala:27)
	at com.twitter.finagle.FactoryToService.apply(FactoryToService.scala:12)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.service.RequeueFilter.$anonfun$applyService$1(RequeueFilter.scala:70)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.MarshalledContext.letLocal(MarshalledContext.scala:157)
	at com.twitter.finagle.context.MarshalledContext.let(MarshalledContext.scala:90)
	at com.twitter.finagle.service.RequeueFilter.applyService(RequeueFilter.scala:70)
	at com.twitter.finagle.service.RequeueFilter.apply(RequeueFilter.scala:110)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:81)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.ClearContextValueFilter$$anon$1$$anon$2.$anonfun$apply$1(ClearContextValueFilter.scala:26)
	at com.twitter.util.Local.let(Local.scala:4979)
	at com.twitter.finagle.context.MarshalledContext.letLocal(MarshalledContext.scala:157)
	at com.twitter.finagle.context.MarshalledContext.letClear(MarshalledContext.scala:108)
	at com.twitter.finagle.filter.ClearContextValueFilter$$anon$1$$anon$2.apply(ClearContextValueFilter.scala:26)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:81)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.Service$$anon$1.apply(Service.scala:16)
	at com.twitter.finagle.filter.ExceptionSourceFilter.apply(ExceptionSourceFilter.scala:50)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:81)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.ServiceProxy.apply(ServiceProxy.scala:12)
	at com.twitter.finagle.filter.RequestLogger$$anon$1$$anon$2.apply(RequestLogger.scala:59)
	at com.twitter.finagle.FactoryToService.$anonfun$apply$1(FactoryToService.scala:13)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1798)
	at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:240)
	at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:240)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:215)
	at com.twitter.util.Promise$WaitQueue.com$twitter$util$Promise$WaitQueue$$run(Promise.scala:91)
	at com.twitter.util.Promise$WaitQueue$$anon$4.run(Promise.scala:86)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise$WaitQueue.runInScheduler(Promise.scala:86)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:776)
	at com.twitter.util.Promise.update(Promise.scala:748)
	at com.twitter.util.Promise.setValue(Promise.scala:724)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelRead(ChannelTransport.scala:172)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.BadRequestHandler$.channelRead0(BadRequestHandler.scala:23)
	at com.twitter.finagle.netty4.http.handler.BadRequestHandler$.channelRead0(BadRequestHandler.scala:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.twitter.finagle.loadbalancer.LazyEndpointFactory$$anon$3: Endpoint Inet(s3.amazonaws.com/52.216.107.206:80,Map()) was marked closed
	at com.twitter.finagle.loadbalancer.LazyEndpointFactory.close(EndpointFactory.scala:142)
	at com.twitter.util.Closable.close(Closable.scala:21)
	at com.twitter.util.Closable.close$(Closable.scala:21)
	at com.twitter.finagle.ServiceFactory.close(ServiceFactory.scala:5)
	at com.twitter.finagle.loadbalancer.TrafficDistributor.$anonfun$weightEndpoints$6(TrafficDistributor.scala:184)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at com.twitter.finagle.loadbalancer.TrafficDistributor.$anonfun$weightEndpoints$1(TrafficDistributor.scala:180)
	at com.twitter.finagle.loadbalancer.TrafficDistributor$.$anonfun$safelyScanLeft$1(TrafficDistributor.scala:65)
	at com.twitter.util.Event$$anon$3.$anonfun$register$3(Event.scala:73)
	at com.twitter.util.Event$$anon$3.$anonfun$register$3$adapted(Event.scala:72)
	at com.twitter.util.Function$.$anonfun$synchronizeWith$1(Function.scala:41)
	at com.twitter.util.Witness$$anon$17.notify(Event.scala:454)
	at com.twitter.util.Var$$anon$3.$anonfun$register$1(Var.scala:102)
	at com.twitter.util.Var$$anon$3.$anonfun$register$1$adapted(Var.scala:101)
	at com.twitter.util.Var$Observer.publish(Var.scala:156)
	at com.twitter.util.Var$Value.observe(Var.scala:232)
	at com.twitter.util.Var$$anon$2.$anonfun$observe$1(Var.scala:80)
	at com.twitter.util.Var$$anon$2.$anonfun$observe$1$adapted(Var.scala:68)
	at com.twitter.util.Var$Observer.publish(Var.scala:156)
	at com.twitter.util.UpdatableVar.$anonfun$update$3(Var.scala:479)
	at com.twitter.util.UpdatableVar.$anonfun$update$3$adapted(Var.scala:474)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:152)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
	at com.twitter.util.UpdatableVar.update(Var.scala:474)
	at com.twitter.finagle.InetResolver$$anon$1.handle(InetResolver.scala:151)
	at com.twitter.finagle.InetResolver$$anon$1.handle(InetResolver.scala:145)
	at com.twitter.finagle.util.Updater.$anonfun$apply$1(Updater.scala:50)
	at com.twitter.finagle.util.Updater.$anonfun$apply$1$adapted(Updater.scala:50)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at com.twitter.finagle.util.Updater.apply(Updater.scala:50)
	at com.twitter.finagle.util.Updater.apply$(Updater.scala:37)
	at com.twitter.finagle.InetResolver$$anon$1.apply(InetResolver.scala:145)
	at com.twitter.finagle.InetResolver.$anonfun$bindHostPortsToAddr$4(InetResolver.scala:155)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at com.twitter.util.Try$.apply(Try.scala:26)
	at com.twitter.util.ExecutorServiceFuturePool$$anon$4.run(FuturePool.scala:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

### Steps to reproduce the behavior

This is has been happening at least since version 18.7.0.  See 
[service-closed.zip](https://github.com/twitter/finagle/files/2715210/service-closed.zip) for a sample project that recreates the behavior.  Note that the sample uses an S3 endpoint, which is where we first observed the behavior (presumably since S3's ip address changes with almost every DNS lookup), but we have also observed it with other endpoints where the IP address changes.

**Comment by yufangong** [comment] 2019-01-11 00:02
@jlawrienyt  Thanks for the reproduce package, I believe this behavior started from 18.6.0, we will look into this issue.

**Comment by yufangong** [comment] 2019-01-17 18:47
@jlawrienyt Thanks for the report, this should be fixed in 815c05315ff47db151a6433c32bcf421c7e1e940. I'm closing this issue now but feel free to open one if the issue still remains.

**Closed by yufangong** 2019-01-17 18:47 UTC

**Comment by jlawrienyt** [comment] 2019-01-17 21:13
Thanks!

**Comment by bebaskar** [comment] 2020-09-24 12:53
This issue is again seen in the finagle-core_2.12. Whenever there is a change in DNS, the connection remains persists & the client is not closing the connection.

 com.twitter.finagle.loadbalancer.LazyEndpointFactory$$anon$1: Tried to acquire endpoint after it was closed
	at ....
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.twitter.finagle.loadbalancer.LazyEndpointFactory$$anon$1: Tried to acquire endpoint after it was closed
	at com.twitter.finagle.loadbalancer.LazyEndpointFactory.apply(EndpointFactory.scala:114)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded$Node.com$twitter$finagle$loadbalancer$LeastLoaded$LeastLoadedNode$$super$apply(P2CLeastLoaded.scala:47)
	at com.twitter.finagle.loadbalancer.LeastLoaded$LeastLoadedNode.apply(LeastLoaded.scala:27)
	at com.twitter.finagle.loadbalancer.LeastLoaded$LeastLoadedNode.apply$(LeastLoaded.scala:25)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded$Node.apply(P2CLeastLoaded.scala:47)
	at com.twitter.finagle.loadbalancer.Balancer.apply(Balancer.scala:211)
	at com.twitter.finagle.loadbalancer.Balancer.apply$(Balancer.scala:199)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded.apply(P2CLeastLoaded.scala:35)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.loadbalancer.TrafficDistributor$Distributor.apply(TrafficDistributor.scala:183)
	at com.twitter.finagle.ServiceFactoryProxy.apply(ServiceFactoryProxy.scala:15)
	at com.twitter.finagle.loadbalancer.TrafficDistributor.apply(TrafficDistributor.scala:420)
