### ISSUE TITLE
If a Filter returns a new RepOut, it causes a deadlock.

### ISSUE THREAD

**Issue by yukw777** [twitter/finagle#498] opened 2016-04-20 21:22 UTC
If you write a Filter that returns a new instance of Response like below, it'll cause a deadlock as the thread that is waiting on the now discarded response will never switch to the new Response returned by the Filter.
```
class DeadlockFilter[Req, Rep] extends SimpleFilter[Req, Rep] {

  def apply(request: Req, service: Service[Req, Rep]): Future[Rep] = Future.value(new Resp)
}
```

It's weird that Filters, that are supposed to be functional, are forcing me to rely on side effects.

**Comment by kevinoliver** [comment] 2016-04-20 22:30
@yukw777 mind leaving a unit test that reproduces along with a stacktrace showing the deadlock?

For what its worth, we do this pretty regularly in Finagle's filters. [TimeoutFilter](https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/service/TimeoutFilter.scala#L151) returning a `Future.exception` is a smallish example.

**Comment by mosesn** [comment] 2016-04-20 23:18
@yukw777 it doesn't seem like 

```scala
class DeadlockFilter[Req, Rep] extends SimpleFilter[Req, Rep] {

  def apply(request: Req, service: Service[Req, Rep]): Future[Rep] = new Resp
}
```

should even compile, since it returns a `Rep`, instead of a `Future[Rep]`.  Is it possible that you're blocking on the response and then rewrapping in a future, instead of transforming the asynchronous response?

**Comment by yukw777** [comment] 2016-04-21 14:32
@mosesn Ah sorry, that was a typo. Fixed now.

**Comment by yukw777** [comment] 2016-04-21 15:11
Hmmm. I dug into it more, and I'm starting to think that I might be misunderstanding the problem. Just to verify my suspicion, please see the snippet below.
```
// http is a http service of type Service[Request, Response]
// resp is a chunked transfer encoded http response
def readAndDoSomethingWithBody(respFuture: Future[Response]): Future[Response] = {
  respFuture.flatMap { resp =>
    Reader.readAll(resp.reader).map {
      case Buf.Utf8(body) if body == "something" => Response()
      case _ => resp
    }
  }
}
for {
  resp <- readAndDoSomethingWithBody(http(req))
  bodyBytes <- Reader.readAll(resp.reader)
} yield {
  // Do something with resp and bodyBytes
}
```

This is the jist of the code that caused a deadlock for me. I'm starting to think that the future that is not resolving and causing the deadlock is `Reader.readAll`, since I'm calling it twice on the same response reader. Is my reasoning correct? If so, is there a way to "reset" the reader, or is it forever gone once it's all read?

**Comment by mosesn** [comment] 2016-04-21 17:07
No, there is no way to reset the reader.  This is intentional, so that servers can stream requests that are bigger than they can fully buffer.  But this should also not block.  `bodyBytes` will just be empty.

**Comment by yukw777** [comment] 2016-04-23 08:27
OK, after a lot of digging, the deadlock was caused by this:
```
resp = Response()
Reader.readAll(resp.reader).map(do something...)
```
Basically, when a `Response` is not chunked, and you try to `readAll` its `reader`, it hangs indefinitely.

Feature? Bug?

**Comment by mosesn** [comment] 2016-04-23 15:24
What do you mean by hang?  Do you mean the `do something` never executes?  From your code, it looks like it's because you haven't written anything to the response's reader, but you also haven't terminated it, so it assumes that it might still send bytes through it.  So I think that's a feature.

**Comment by yukw777** [comment] 2016-04-23 17:19
That's exactly what I meant.

Sorry to keep asking questions, but I've tried the following code per your suggestion of terminating my response's reader. However, it still hangs!

```
val resp = Response()
Await.result(
  resp.close()
  .flatMap(Unit =>
    Reader.readAll(resp.reader)
    .map(buf => println(buf.isEmpty))))
```

Maybe this is not the way to terminate the reader?

**Comment by mosesn** [comment] 2016-05-29 03:20
@yukw777 I'm so sorry, I missed your response!  I'm trying it out now.  This might be a bug.

**Comment by mosesn** [comment] 2016-05-29 03:26
@yukw777 OK, so I tried it in the repl, and I think your code is right except for one small thing, which is that close will not be satisfied until what is written has been fully read.

Here's the result of playing around in the repl.

```scala
scala> import com.twitter.finagle.http.Response
import com.twitter.finagle.http.Response

scala> import com.twitter.util.Await
import com.twitter.util.Await

scala> val resp = Response()
resp: com.twitter.finagle.http.Response = Response("HTTP/1.1 Status(200)")

scala> resp.close()
res0: com.twitter.util.Future[Unit] = Promise@464042769(state=Waiting(null,List()))

scala> res0
res1: com.twitter.util.Future[Unit] = Promise@464042769(state=Waiting(null,List()))

scala> import com.twitter.io.Reader
import com.twitter.io.Reader

scala> Reader.readAll(resp.reader)
res2: com.twitter.util.Future[com.twitter.io.Buf] = Promise@92341597(state=Done(Return(com.twitter.io.Buf$NoopBuf@811c9dc5)))

scala> res2.onSuccess { buf => println(buf.isEmpty) }
true
res3: com.twitter.util.Future[com.twitter.io.Buf] = Future@595450727(depth=1,parent=Promise@92341597(state=Done(Return(com.twitter.io.Buf$NoopBuf@811c9dc5))))

scala> res0
res4: com.twitter.util.Future[Unit] = Promise@464042769(state=Done(Return(())))
```

So I think it works, but your flatMap closure was never executed because it couldn't be executed until after close was satisfied, and close couldn't be satisfied until after the flatMap closure was run!

Hopefully this answers your question.  I'm closing this ticket for now, but please reopen if you have more questions.

**Closed by mosesn** 2016-05-29 03:26 UTC
