### ISSUE TITLE
Feature Request / Question: Load balancer with no rotation

### ISSUE THREAD

**Issue by johanstenberg92** [twitter/finagle#496] opened 2016-04-18 18:34 UTC
Hi,

I'm using Finagle for my Master's Thesis project and so far, I'm really liking it! Thanks for a great library.

My thesis involves creating a distributed, resilient in-memory database, which is using strong eventual consistency. With strong eventual consistency, I want to be able to create a finagle client, tell it it's closest replicas but since the synchronization between replicas aren't instant, I don't want any rotation (think that you write a value then read it and it isn't there...). However I still want the client to auto-magically change replica if the first replica is down.

I've whipped up a very simple load balancer which sticks with the same node until it needs to change because of the status of the node has changed, would this be an interesting PR or maybe it's too trivial?

Finally, I would like to know if I should approach this problem any other way, I haven't found any other way in your docs. It might be semantically odd to have it reconnect to another replica instantly.

Thanks!

**Comment by vkostyukov** [comment] 2016-04-18 19:16
Thanks a lot for sharing this @johanstenberg92, this is really interesting!

I wonder if having a tiny wrapper around `ServiceFactory` returned from `$Ptotocol.newClient` would allow you to achieve that. When you ask for a client (`newClient: ServiceFactory`) not a service (`newService: Service`), it provides you more fine grained control over the underlying session (represented as a `Service`), which maps to a concrete replica and concrete connection. So basically you can create one and used it until `status != open` so you can recreate that and use again.

Hope that's not complete non-sense.

**Comment by olix0r** [comment] 2016-04-18 20:58
I had a similar use case recently, and @mosesn suggested that the _aperture_ load balancer could be used with `maxEffort = Int.MaxValue (see https://github.com/BuoyantIO/linkerd/pull/300).  This should cause _all_ traffic to be sent to a single endpoint as long as that endpoint is available. When it is no longer available another endpoint in the load balancing pool will be used.

**Comment by johanstenberg92** [comment] 2016-04-19 06:35
@vkostyukov and @olix0r thanks for replying. I've solved it by creating my own load-balancer.

Would a PR be interesting to take a look at @vkostyukov? With a new load balancer? Otherwise you are free to close this!

**Comment by mosesn** [comment] 2016-04-19 15:17
I think it would be useful.  A few people have asked about it, so clearly there's a use for it.

**Comment by johanstenberg92** [comment] 2016-04-19 17:28
@mosesn cool, I'll create a PR in the next 24h and reference this issue, cheers!

**Comment by roanta** [comment] 2016-04-20 16:44
I agree with @vkostyukov, why can't we build this on top of a client using the ServiceFactory API? That's the intended use case.

**Comment by mariusae** [comment] 2016-04-21 16:46
So, there are pretty deep-seated assumptions inside of Finagle that service clusters are homogenous, that they are equivalent from the point of view of the application.

If you have application semantics that violate this assumption, it should be built on top of the services (or service factories) that are given to you by Finagle, as suggested by @vkostyukov and @roanta.

Moreover, Finagle makes this pretty simple, due to the uniform nature of its abstractions.

**Comment by mosesn** [comment] 2016-04-21 17:02
@mariusae I don't think sticky sessions violate this, as long as it's an optimization.  If each remote host responds the same way, except that it can provide better information if it knows what it last gave the peer, that will work too.

Consider the case where you care about the members of a given set (say, service discovery).  The contract clients and servers have is that a client connects to a single server, and then it gets a full copy of the members.  On subsequent updates, the server can now choose whether to give it diffs or a full copy.  It doesn't violate the assumption that service clusters are homogeneous, and the client doesn't care that it had to keep talking to the same server to get the diffs.  It's purely an optimization.

We may want to do this if we start backing a server like this with a wily name, and want to be able to fail over to another such server using wily.

With that said, it does break requeues, but aperture of size one does too until failure accrual kicks in, so this seems harmless.

**Comment by mariusae** [comment] 2016-04-21 17:05
@mosesn the problem is that it's an *application level* optimization; the trick is used to get more up-to-date reads from the underlying system. Compare with, e.g., the optimizations presented by aperture itself which is more about resource conservation and load balancing.

**Comment by mosesn** [comment] 2016-04-21 17:15
@mariusae this seems OK to me–the same way that finagle-memcached assumes that you'll talk to shards as if they're shards, and not as if they're replicas.

If we end up in a future where finagle is more modular, we will be able to swap out the load balancer for a sticky session chooser, and choose to layer sharding on top.  You can imagine a cache client which also has a small fixed-size in-memory cache that the shard can choose to update with hot keys.

With that said, from talking to folks who are using aperture of size one, and @johanstenberg92, it sounds like none of them actually need naming, which is the only reason to put this at the load balancing layer, as far as I can tell, so we're going to close this ticket.

**Closed by mosesn** 2016-04-21 17:15 UTC

**Comment by mariusae** [comment] 2016-04-21 17:21
@mosesn but shard management is built on top of the standard finagle stack.

**Comment by mosesn** [comment] 2016-04-21 17:29
@mariusae sort of?  it's basically an implementation detail today.  the API we expose is the same regular finagle protocol one, and we will probably move shard management into the normal stack so that we can use names.
