### ISSUE TITLE
Framed transport client saw out of order responses from finagle server

### ISSUE THREAD

**Issue by newpoo** [twitter/finagle#790] opened 2019-08-25 04:39 UTC
Framed transport client saw out of order responses on the same connection from finagle server

### Expected behavior

As far as I understand, framed transport doesn't allow out of order responses on the same connection

### Actual behavior

Framed transport client saw out of order responses on the same connection from finagle server

### Steps to reproduce the behavior

We use fbthfit c++ client with binary protocol and Framed transport.

**Comment by mosesn** [comment] 2019-08-25 13:37
Interesting!  Is fbthrift trying to use pipelining, where you can send more than one request on a given connection and receive responses in order?  Or multiplexing, where you can receive responses out of order?  Finagle Thrift clients can't do pipelining (instead, thriftmux supports multiplexing) so we haven't tested it too elaborately.  Some googling seems to suggest that at least some Apache Thrift servers [support pipelining][0].  Unlike fbthrift, thrift doesn't have a THeader, so it can't support multiplexing.

From looking at the [code][1], it looks like it shouldn't read the next message until after it has already replied to the previous message, so I don't understand how messages could be received out of order.  Would you mind writing a unit test that demonstrates the problem?

[0]: https://github.com/apache/thrift/blob/master/doc/specs/thrift-rpc.md#thrift-remote-procedure-call-message-exchange
[1]: https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/dispatch/ServerDispatcher.scala

**Comment by newpoo** [comment] 2019-08-25 14:43
Yes, we use fbthrift c++ async client with framed binary protocol, which support pipelining but not multiplexing.

I think the server side is running with finagle-thriftmux_2.11.

We can try to provide more details later.

**Comment by newpoo** [comment] 2019-08-25 14:53
"From looking at the code, it looks like it shouldn't read the next message until after it has already replied to the previous message, " 

Do you mean until after it has already written the response to the underlying tcp connection or some finagle internal data structure?

**Comment by bryce-anderson** [comment] 2019-11-01 22:56
@newpoo, any luck with this? If you can setup a repro that would be really helpful.

**Comment by newpoo** [comment] 2019-11-01 23:14
We had to switch back to nonmux server and the issue is gone. It's highly likely a bug in binary protocol pipelining support in thriftmux server.

**Comment by bryce-anderson** [comment] 2019-11-01 23:28
Any chance you can explain a repro?

**Comment by bryce-anderson** [comment] 2019-11-01 23:32
Info such as if it happened during restarts, etc would be helpful.

**Comment by newpoo** [comment] 2019-11-01 23:47
It's consistently happening when we use binary protocol client talk to finagle thriftmux server with pipelining (multiple outstanding requests on a single connection). We expect to see responses coming back in order. However, the responses can be out of order. It's easier to see this issue when the server CPU load is high.

**Comment by bryce-anderson** [comment] 2019-11-02 02:33
I'm unable to reproduce this. Do you know how many requests it takes? I whipped together a test that throws 200k pipelined requests through a downgraded thriftmux session in about 15 seconds and have yet to see an out-of-order response. 

How are you detecting out-of-order responses?

**Comment by newpoo** [comment] 2019-11-02 05:01
In our thrift API, response has the key that was sent in the original request. So we can detect the mismatches.

what does the server handler function do? try to add some random delay in the handler function?

**Comment by bryce-anderson** [comment] 2019-11-02 13:27
My test sends numbers that get echoed back. Both requests and responses
have a a random delay between 0 and 50 ms.

**Comment by mosesn** [comment] 2019-12-06 17:38
@newpoo since we're not able to reproduce, I'm inclined to close this ticket, unless you have more suggestions for how we can repro?

**Comment by bryce-anderson** [comment] 2020-02-06 15:45
Closing since we couldn't repro this. If someone can get a repro case please reopen!

**Closed by bryce-anderson** 2020-02-06 15:45 UTC
Labels: waiting
