### ISSUE TITLE
FinestIOExceptionMessages to include "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by clumsy** [twitter/finagle#533] opened 2016-07-29 20:29 UTC
When the socket is closed from the client side`IOException` "An existing connection was forcibly closed by the remote host" is rethrown by Netty.
`ServerBridge` checks the message and based on that decides the level for the log message.
### Expected behavior

This message has to be logged with FINEST level
### Actual behavior

The message is logged with WARNING level
### Steps to reproduce the behavior

Start the service, connect the client, stop the client.

**Comment by mosesn** [comment] 2016-07-29 22:57
@clumsy do you mind making a small reproduction case?  Would love to reproduce it locally so it's simpler for us to investigate.

**Comment by bryce-anderson** [comment] 2016-07-29 23:06
@clumsy, are you working on a Windows machine? [This](https://github.com/http4s/blaze/blob/81d5d0d8f825cf588ff1ef433bf418a386506669/core/src/main/scala/org/http4s/blaze/channel/ChannelHead.scala#L43) bit of code looks like it addresses the same thing.

**Comment by clumsy** [comment] 2016-07-30 01:00
@bryce-anderson yes, I'm working on Windows. Looks like the message is different in that case.
Can this be incorporated into finagle?
Sorry, cannot contribute as I don't use Scala.

**Comment by mosesn** [comment] 2016-07-30 01:09
@clumsy hmm, looks like it should be pretty simple.  I think just adding a string to a set [here][0].

Do you mind taking a stab at it?  None of us can test it, since we don't have windows machines.  It's a pretty minimal use of scala.

[0]: https://github.com/twitter/finagle/blob/develop/finagle-core/src/main/scala/com/twitter/finagle/netty3/Netty3Listener.scala#L349-L354

**Comment by clumsy** [comment] 2016-07-30 01:41
No problem, it's just I won't be compiling it.

**Comment by mosesn** [comment] 2016-07-30 02:31
We can probably help you with compiling it.  `finagle` comes with everything you need, so it should be pretty straightforward.  We need you to try compiling it so we can make sure it's fixed on your platform!

**Comment by clumsy** [comment] 2016-07-30 03:40
@mosesn I knew it wouldn't be simple...
I tried running via both standalone sbt and from the script.
Keeps complaining about missing 4.8.0-SNAPHOT of scrooge:

```
[warn]  Note: Unresolved dependencies path:
[warn]          com.twitter:scrooge-sbt-plugin:4.8.0-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10) (/Users/alexander_jipa/Projects/scala/finagle/project/plugins.sbt#L9-10)
[warn]            +- default:finagle-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
sbt.ResolveException: unresolved dependency: com.twitter#scrooge-sbt-plugin;4.8.0-SNAPSHOT: not found
```

After traversing the fields found Build.scala with funny logic: 

```scala
...
  val suffix = if (branch == "master") "" else "-SNAPSHOT"

  val libVersion = "6.36.0" + suffix
  val utilVersion = "6.35.0" + suffix
  val ostrichVersion = "9.19.0" + suffix
  val scroogeVersion = "4.8.0" + suffix
...
```

Only builds from `master` branch...

**Comment by mosesn** [comment] 2016-07-30 21:48
that's something we do to make it easier to make changes across repositories.  if you can emulate bash on windows, we recently made a shell script that makes it easier to build multiple projects using sbt: https://github.com/twitter/dodo

**Comment by mosesn** [comment] 2017-05-10 20:57
@clumsy added this back here: https://github.com/twitter/finagle/commit/e649e9ebea74da741deda2ff9b41361ed19e2e46 thanks!

**Closed by mosesn** 2017-05-10 20:57 UTC
Labels: Starter
